# Generated by Django 4.1.7 on 2023-04-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_bid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
