# Generated by Django 4.1.7 on 2023-04-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='entred_bidding_room_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
