# Generated by Django 4.1 on 2023-04-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_entred_bidding_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alloted_mechanic',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
