# Generated by Django 4.1 on 2023-04-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_alloted_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='call_credit',
            field=models.IntegerField(default=0),
        ),
    ]
