# Generated by Django 4.1.4 on 2023-07-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customer_call_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=2000000000000000000000000),
        ),
    ]
