# Generated by Django 4.1.7 on 2023-04-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bidding_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('chassis_no', models.CharField(max_length=100)),
                ('engine_no', models.CharField(max_length=100)),
                ('automatic_generated_bid_id', models.CharField(default='', max_length=4)),
                ('year', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('modified', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('car_location', models.CharField(max_length=100)),
                ('images_normal', models.ImageField(upload_to='')),
                ('allowed', models.BooleanField()),
                ('engine_type', models.CharField(max_length=100)),
                ('engine_cap', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('Assembly', models.CharField(max_length=100)),
                ('air_bags', models.BooleanField()),
                ('alloy_wheels', models.BooleanField()),
                ('immoblizer', models.BooleanField()),
                ('ac', models.BooleanField()),
                ('coolbox', models.BooleanField()),
                ('power_door_locks', models.BooleanField()),
                ('abs', models.BooleanField()),
                ('folding_seats', models.BooleanField()),
                ('all_wheel_drive', models.BooleanField()),
                ('images_modeling', models.ImageField(upload_to='')),
                ('bidding_title', models.CharField(max_length=100)),
                ('bidding_price', models.CharField(max_length=100)),
                ('bidding_desc', models.CharField(max_length=100)),
                ('bidding_date', models.DateField()),
                ('bidding_time', models.TimeField()),
            ],
        ),
    ]
