# Generated by Django 4.1.7 on 2023-04-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding_car',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
