# Generated by Django 4.1.7 on 2023-04-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_alter_bidding_car_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding_car',
            name='Assembly',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='abs',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='ac',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='air_bags',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='all_wheel_drive',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='alloy_wheels',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='bidding_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='bidding_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='bidding_price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='bidding_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='bidding_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='coolbox',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='engine_cap',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='engine_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='folding_seats',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='images_modeling',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='immoblizer',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='power_door_locks',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='transmission',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
