# Generated by Django 4.1.7 on 2023-04-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_alter_bidding_car_assembly_alter_bidding_car_abs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding_car',
            name='images_normal',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bidding_car',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
