# Generated by Django 4.1.4 on 2023-04-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessorie', '0002_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ptype',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
