# Generated by Django 4.1.4 on 2023-04-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessorie', '0003_products_ptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=5)),
                ('cname', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('zipcode', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('product_ids', models.CharField(max_length=100)),
            ],
        ),
    ]
