# Generated by Django 4.1.4 on 2023-06-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessorie', '0005_products_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_urls',
        ),
    ]
