# Generated by Django 4.1.4 on 2023-06-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessorie', '0007_order_quantity_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
