# Generated by Django 4.1.4 on 2023-06-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessorie', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
