# Generated by Django 4.1.7 on 2023-04-01 13:10

import car_bidding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bidding_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('chassis_no', models.CharField(max_length=100)),
                ('engine_no', models.CharField(max_length=100)),
                ('automatic_generated_bid_id', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('modified', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('car_location', models.CharField(max_length=100)),
                ('miniform_approved', models.BooleanField(default=False)),
                ('engine_type', models.CharField(blank=True, default='', max_length=100, validators=[car_bidding.models.validate_miniform_approved])),
                ('engine_capacity', models.CharField(blank=True, default='', max_length=100, validators=[car_bidding.models.validate_miniform_approved])),
                ('transmission', models.CharField(blank=True, default='', max_length=100, validators=[car_bidding.models.validate_miniform_approved])),
                ('assembly', models.CharField(blank=True, default='', max_length=100, validators=[car_bidding.models.validate_miniform_approved])),
                ('ad_title', models.CharField(blank=True, default='', max_length=100, validators=[car_bidding.models.validate_miniform_approved])),
                ('ad_description', models.CharField(blank=True, default='', max_length=100, validators=[car_bidding.models.validate_miniform_approved])),
                ('bid_date', models.DateField(blank=True, default='2020-02-22', validators=[car_bidding.models.validate_miniform_approved])),
                ('bid_time', models.TimeField(blank=True, default='00:00:00', validators=[car_bidding.models.validate_miniform_approved])),
                ('airbags', models.BooleanField(default=False, validators=[car_bidding.models.validate_miniform_approved])),
                ('alloy_wheels', models.BooleanField(default=False, validators=[car_bidding.models.validate_miniform_approved])),
                ('immoblizer', models.BooleanField(default=False, validators=[car_bidding.models.validate_miniform_approved])),
                ('ac', models.BooleanField(default=False, validators=[car_bidding.models.validate_miniform_approved])),
                ('cool_box', models.BooleanField(default=False, validators=[car_bidding.models.validate_miniform_approved])),
                ('folding_seats', models.BooleanField(default=False, validators=[car_bidding.models.validate_miniform_approved])),
                ('power_door_locks', models.BooleanField(default=False, validators=[car_bidding.models.validate_miniform_approved])),
                ('antibrakingsystem', models.BooleanField(default=False, validators=[car_bidding.models.validate_miniform_approved])),
            ],
        ),
    ]
