# Generated by Django 4.1.7 on 2023-04-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0003_bidding_calender_bid_date_down_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding_calender',
            old_name='bid_date_down',
            new_name='bid_datetime_left',
        ),
        migrations.RemoveField(
            model_name='bidding_calender',
            name='bid_time_down',
        ),
    ]
