# Generated by Django 4.1.7 on 2023-04-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0004_rename_bid_date_down_bidding_calender_bid_datetime_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding_calender',
            name='bid_datetime_left',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
