# Generated by Django 4.1.7 on 2023-04-01 16:05

import car_bidding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0005_alter_bidding_calender_bid_datetime_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidding_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic_generated_bid_id', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('modified', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('engine_type', models.CharField(blank=True, default='', max_length=100, validators=[car_bidding.models.validate_miniform_approved])),
                ('engine_capacity', models.CharField(blank=True, default='', max_length=100, validators=[car_bidding.models.validate_miniform_approved])),
                ('transmission', models.CharField(blank=True, default='', max_length=100, validators=[car_bidding.models.validate_miniform_approved])),
                ('assembly', models.CharField(blank=True, default='', max_length=100, validators=[car_bidding.models.validate_miniform_approved])),
                ('ad_title', models.CharField(blank=True, default='', max_length=100, validators=[car_bidding.models.validate_miniform_approved])),
                ('bid_datetime_left', models.CharField(blank=True, default='', max_length=100)),
                ('staring_bid', models.CharField(blank=True, default='', max_length=100)),
                ('increase_bid', models.CharField(blank=True, default='', max_length=100)),
                ('higest_bid', models.CharField(blank=True, default='', max_length=100)),
                ('bid_winner', models.CharField(blank=True, default='', max_length=100)),
                ('current_bid', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bidding_calender',
            name='staring_bid',
            field=models.CharField(blank=True, default='5,00,000', max_length=100),
        ),
    ]
