# Generated by Django 4.1.7 on 2023-04-01 16:28

import car_bidding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0006_bidding_room_bidding_calender_staring_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding_car',
            name='room_id',
            field=models.CharField(blank=True, default=' ', max_length=3, validators=[car_bidding.models.validate_miniform_approved]),
        ),
        migrations.AddField(
            model_name='bidding_room',
            name='room_id',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
