# Generated by Django 4.1.7 on 2023-04-01 16:41

import car_bidding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0008_rename_staring_bid_bidding_room_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding_car',
            name='starting_bid',
            field=models.CharField(blank=True, default=' ', max_length=20000, validators=[car_bidding.models.validate_miniform_approved]),
        ),
    ]
