# Generated by Django 4.1.7 on 2023-04-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0009_bidding_car_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding_car',
            name='room_id_alloted',
            field=models.BooleanField(default=False),
        ),
    ]
