# Generated by Django 4.1.7 on 2023-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0010_bidding_car_room_id_alloted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding_room',
            name='highest_bidder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bidding_room',
            name='increase_bid',
            field=models.CharField(blank=True, default='5000', max_length=100),
        ),
    ]
