# Generated by Django 4.1 on 2023-07-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0011_bidding_room_highest_bidder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidding_car_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bidding_car_images/')),
            ],
        ),
        migrations.AddField(
            model_name='bidding_car',
            name='images',
            field=models.ManyToManyField(blank=True, to='car_bidding.bidding_car_image'),
        ),
    ]
