# Generated by Django 4.1.4 on 2023-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_bidding", "0011_bidding_room_highest_bidder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="bidding_car_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="bidding_car_images/")),
            ],
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="ac",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="ad_description",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="ad_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="airbags",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="alloy_wheels",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="antibrakingsystem",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="assembly",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="bid_date",
            field=models.DateField(blank=True, default="2020-02-22"),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="bid_time",
            field=models.TimeField(blank=True, default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="cool_box",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="engine_capacity",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="engine_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="folding_seats",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="immoblizer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="power_door_locks",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="room_id",
            field=models.CharField(blank=True, default=" ", max_length=3),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="starting_bid",
            field=models.CharField(blank=True, default=" ", max_length=20000),
        ),
        migrations.AlterField(
            model_name="bidding_car",
            name="transmission",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="bidding_room",
            name="images",
            field=models.ManyToManyField(
                blank=True, to="car_bidding.bidding_car_image"
            ),
        ),
    ]
