# Generated by Django 4.1 on 2023-07-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0012_bidding_car_image_bidding_car_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding_room',
            name='ad_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bidding_room',
            name='assembly',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bidding_room',
            name='engine_capacity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bidding_room',
            name='engine_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bidding_room',
            name='transmission',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
