# Generated by Django 4.1.4 on 2023-07-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_bidding", "0013_bidding_car_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidding_room",
            name="start_date",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="bidding_room",
            name="start_time",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
