# Generated by Django 4.1 on 2023-07-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0013_alter_bidding_room_ad_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding_car',
            name='images',
        ),
        migrations.AddField(
            model_name='bidding_room',
            name='images',
            field=models.ManyToManyField(blank=True, to='car_bidding.bidding_car_image'),
        ),
    ]
