# Generated by Django 4.1.4 on 2023-07-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_bidding", "0014_bidding_room_start_date_bidding_room_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidding_room",
            name="images",
        ),
        migrations.AddField(
            model_name="bidding_car",
            name="images",
            field=models.ManyToManyField(
                blank=True, to="car_bidding.bidding_car_image"
            ),
        ),
    ]
