# Generated by Django 4.1.4 on 2023-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_bidding", "0015_remove_bidding_room_images_bidding_car_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_data", models.TextField()),
            ],
        ),
    ]
