# Generated by Django 4.1.4 on 2023-07-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0015_alter_bidding_car_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding_car',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
