# Generated by Django 4.1.4 on 2023-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bidding', '0016_bidding_car_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding_room',
            name='images',
        ),
        migrations.AddField(
            model_name='bidding_car',
            name='images',
            field=models.ManyToManyField(blank=True, to='car_bidding.bidding_car_image'),
        ),
        migrations.AddField(
            model_name='bidding_room',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bidding_room',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
