# Generated by Django 4.1 on 2023-04-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mechanic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic_generated_M_ticket_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('m_id', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='mechanic',
            name='assigned_m_ticket_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
