# Generated by Django 4.1 on 2023-04-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mechanic', '0002_mechanic_ticket_mechanic_assigned_m_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic_ticket',
            name='closed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
