# Generated by Django 4.1 on 2023-04-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mechanic', '0003_mechanic_ticket_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=5)),
                ('skills', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
