# Generated by Django 4.1 on 2023-04-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mechanic', '0004_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='e_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
