# Generated by Django 4.1 on 2023-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mechanic', '0005_expert_e_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='assigned_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
