# Generated by Django 4.1.4 on 2023-07-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mechanic", "0006_expert_assigned_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mechanic",
            name="assigned_customer_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
