# Generated by Django 4.1.4 on 2023-07-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mechanic", "0007_alter_mechanic_assigned_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="description",
            field=models.TextField(),
        ),
    ]
