# Generated by Django 4.1.4 on 2023-06-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=5)),
                ('pname', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='car_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('ptype', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UsedCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.EmailField(max_length=254, null=True)),
                ('cid', models.CharField(max_length=5)),
                ('bodytype', models.CharField(max_length=100)),
                ('reg_city', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('variant', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=200)),
                ('engine_capacity', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=200)),
                ('assembly', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_phone', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('images', models.ImageField(upload_to='car_images')),
                ('airbags', models.BooleanField(default=False)),
                ('airconditioner', models.BooleanField(default=False)),
                ('alloywheels', models.BooleanField(default=False)),
                ('antilockbreakingsystem', models.BooleanField(default=False)),
                ('coolbox', models.BooleanField(default=False)),
                ('cupholders', models.BooleanField(default=False)),
                ('foldingrearseat', models.BooleanField(default=False)),
                ('immobilizer', models.BooleanField(default=False)),
                ('powerdoorlocks', models.BooleanField(default=False)),
                ('powersteering', models.BooleanField(default=False)),
                ('powerwindows', models.BooleanField(default=False)),
                ('powermirrors', models.BooleanField(default=False)),
                ('rearwiper', models.BooleanField(default=False)),
                ('tractioncontrol', models.BooleanField(default=False)),
                ('rearseatent', models.BooleanField(default=False)),
                ('climatecontrol', models.BooleanField(default=False)),
                ('rearacvents', models.BooleanField(default=False)),
                ('frontspeaker', models.BooleanField(default=False)),
                ('rearspeaker', models.BooleanField(default=False)),
                ('armrests', models.BooleanField(default=False)),
            ],
        ),
    ]
