# Generated by Django 4.1.4 on 2023-06-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usedcars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
