# Generated by Django 4.1.4 on 2023-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedcars', '0002_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcars',
            name='cid',
            field=models.CharField(max_length=6),
        ),
    ]
