# Generated by Django 4.1.4 on 2023-07-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usedcars", "0003_alter_usedcars_cid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usedcars",
            name="airbags",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="airconditioner",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="alloywheels",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="antilockbreakingsystem",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="armrests",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="climatecontrol",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="coolbox",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="cupholders",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="foldingrearseat",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="frontspeaker",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="immobilizer",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="powerdoorlocks",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="powermirrors",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="powersteering",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="powerwindows",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="rearacvents",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="rearseatent",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="rearspeaker",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="rearwiper",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="tractioncontrol",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
