# Generated by Django 4.1.4 on 2023-07-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usedcars",
            "0004_alter_usedcars_airbags_alter_usedcars_airconditioner_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usedcars",
            name="airbags",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="airconditioner",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="alloywheels",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="antilockbreakingsystem",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="armrests",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="climatecontrol",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="coolbox",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="cupholders",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="foldingrearseat",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="frontspeaker",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="immobilizer",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="powerdoorlocks",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="powermirrors",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="powersteering",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="powerwindows",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="rearacvents",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="rearseatent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="rearspeaker",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="rearwiper",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="tractioncontrol",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
