# Generated by Django 4.1.4 on 2023-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usedcars",
            "0005_alter_usedcars_airbags_alter_usedcars_airconditioner_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="used_car_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="car_images/")),
            ],
        ),
        migrations.RemoveField(
            model_name="usedcars",
            name="images",
        ),
        migrations.AddField(
            model_name="usedcars",
            name="images",
            field=models.ManyToManyField(blank=True, to="usedcars.used_car_image"),
        ),
    ]
