# Generated by Django 4.1.4 on 2023-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usedcars", "0006_used_car_image_remove_usedcars_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usedcars",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="cars", to="usedcars.used_car_image"
            ),
        ),
    ]
