# Generated by Django 4.1.4 on 2023-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usedcars", "0007_alter_usedcars_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_data", models.TextField()),
            ],
        ),
    ]
