# Generated by Django 4.1.4 on 2023-07-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usedcars", "0008_imagemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="used_car_image",
            name="image",
            field=models.ImageField(upload_to="used_car_image/"),
        ),
    ]
