# Generated by Django 4.1.4 on 2023-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usedcars", "0009_alter_used_car_image_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageModel",
        ),
        migrations.AlterField(
            model_name="usedcars",
            name="images",
            field=models.ManyToManyField(blank=True, to="usedcars.used_car_image"),
        ),
    ]
